"""
Test different exit rules for XAUUSD H1 MOM20 strategy.
"""
import os
import sys

import pandas as pd
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from backtest.execution import ExecutionConfig, ExecutionSimulator
from backtest.metrics import calculate_metrics, print_metrics
from logger import setup_logger

logger = setup_logger("exit_research")


def compute_atr(df, period=20):
    tr1 = df["high"] - df["low"]
    tr2 = (df["high"] - df["close"].shift()).abs()
    tr3 = (df["low"] - df["close"].shift()).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    return tr.rolling(period).mean()


def backtest_with_exits(data, base_signals, exit_rule="none", exit_param=None, exec_cfg=None):
    """
    Simulate strategy with various exit rules.
    
    base_signals: Series of -1, 0, 1 (generated by momentum strategy)
    exit_rule: "none", "time", "atr_stop", "trailing"
    """
    close = data["close"]
    high = data["high"]
    low = data["low"]
    atr = compute_atr(data, 20)
    
    positions = pd.Series(0.0, index=data.index)
    entry_price = None
    entry_bar = None
    best_price = None  # For trailing stop
    
    for i in range(len(data)):
        t = data.index[i]
        base_sig = base_signals.iloc[i]
        
        if positions.iloc[i-1] == 0 if i > 0 else True:
            # Not in position — enter if signal says so
            if base_sig != 0:
                positions.iloc[i] = base_sig
                entry_price = close.iloc[i]
                entry_bar = i
                best_price = close.iloc[i]
            else:
                positions.iloc[i] = 0
        else:
            # In position — check exit rules
            current_pos = positions.iloc[i-1]
            
            # Update best price for trailing stop
            if current_pos == 1:
                best_price = max(best_price, high.iloc[i])
            else:
                best_price = min(best_price, low.iloc[i])
            
            exit_triggered = False
            
            if exit_rule == "time" and exit_param is not None:
                if i - entry_bar >= exit_param:
                    exit_triggered = True
            
            elif exit_rule == "atr_stop" and exit_param is not None:
                atr_val = atr.iloc[i]
                if pd.notna(atr_val):
                    if current_pos == 1 and close.iloc[i] < entry_price - exit_param * atr_val:
                        exit_triggered = True
                    elif current_pos == -1 and close.iloc[i] > entry_price + exit_param * atr_val:
                        exit_triggered = True
            
            elif exit_rule == "trailing" and exit_param is not None:
                atr_val = atr.iloc[i]
                if pd.notna(atr_val):
                    if current_pos == 1 and close.iloc[i] < best_price - exit_param * atr_val:
                        exit_triggered = True
                    elif current_pos == -1 and close.iloc[i] > best_price + exit_param * atr_val:
                        exit_triggered = True
            
            # Also exit if base signal flipped
            if base_sig != current_pos:
                exit_triggered = True
            
            if exit_triggered:
                positions.iloc[i] = 0
                entry_price = None
                entry_bar = None
                best_price = None
            else:
                positions.iloc[i] = current_pos
    
    # Shift positions by 1 to avoid lookahead
    positions = positions.shift(1).fillna(0)
    
    # Calculate returns
    price_ret = close.pct_change().fillna(0)
    strat_ret = positions * price_ret
    
    # Apply costs
    sim = ExecutionSimulator(exec_cfg or ExecutionConfig(commission_per_lot=7.0, trade_lots=1.0))
    strat_ret = sim.apply_costs_to_returns(data, strat_ret, positions)
    
    equity = 100_000 * (1 + strat_ret).cumprod()
    metrics = calculate_metrics(equity, periods_per_year=365*24)
    
    # Count trades
    trades = positions[positions != 0].groupby((positions == 0).cumsum()).count()
    num_trades = len(trades[trades > 0])
    metrics["num_trades"] = num_trades
    
    return metrics


def main():
    df = pd.read_parquet("data/raw/XAUUSD_H1.parquet")
    df["time"] = pd.to_datetime(df["time"], utc=True)
    df = df.sort_values("time").reset_index(drop=True)
    df = df.set_index("time")
    
    # Base momentum signals
    mom = df["close"].pct_change(20)
    base_signals = pd.Series(0, index=df.index)
    base_signals[mom > 0] = 1
    base_signals[mom < 0] = -1
    
    exec_cfg = ExecutionConfig(commission_per_lot=7.0, trade_lots=1.0)
    
    variants = [
        ("Base (hold until flip)", "none", None),
        ("Time stop 24 bars", "time", 24),
        ("Time stop 48 bars", "time", 48),
        ("Time stop 72 bars", "time", 72),
        ("ATR stop 1.5x", "atr_stop", 1.5),
        ("ATR stop 2.0x", "atr_stop", 2.0),
        ("ATR stop 3.0x", "atr_stop", 3.0),
        ("Trailing stop 2x ATR", "trailing", 2.0),
        ("Trailing stop 3x ATR", "trailing", 3.0),
        ("Trailing stop 4x ATR", "trailing", 4.0),
    ]
    
    results = []
    for name, rule, param in variants:
        logger.info(f"Testing: {name}")
        metrics = backtest_with_exits(df, base_signals, rule, param, exec_cfg)
        results.append({
            "variant": name,
            "sharpe": metrics.get("sharpe_ratio", np.nan),
            "total_return_pct": metrics.get("total_return_pct", np.nan),
            "ann_return_pct": metrics.get("ann_return_pct", np.nan),
            "max_dd_pct": metrics.get("max_drawdown_pct", np.nan),
            "num_trades": metrics.get("num_trades", 0),
            "win_rate_pct": metrics.get("win_rate_pct", np.nan),
            "profit_factor": metrics.get("profit_factor", np.nan),
        })
        logger.info(f"  Sharpe={metrics.get('sharpe_ratio', 0):.3f} "
                   f"Ret={metrics.get('total_return_pct', 0):.1f}% "
                   f"DD={metrics.get('max_drawdown_pct', 0):.1f}% "
                   f"Trades={metrics.get('num_trades', 0)}")
    
    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values("sharpe", ascending=False)
    
    print("\n" + "=" * 80)
    print("EXIT RULE COMPARISON")
    print("=" * 80)
    print(results_df.to_string(index=False))
    
    os.makedirs("data/processed", exist_ok=True)
    results_df.to_csv("data/processed/exit_research.csv", index=False)


if __name__ == "__main__":
    main()
