//+------------------------------------------------------------------+
//| AUDUSD M5 Compression Breakout - PAPER FORWARD EA                 |
//| Generated by CoreEA EdgeLab                                       |
//|                                                                  |
//| SAFE DEFAULT: PaperMode=true. It logs signals and virtual trades  |
//| instead of sending real orders. Do not enable live trading until  |
//| paper-forward evidence is collected.                              |
//+------------------------------------------------------------------+
#property strict
#property version   "1.001"
#property description "AUDUSD M5 compression breakout paper-forward tracker"

#include <Trade/Trade.mqh>

input bool   PaperMode              = true;
input bool   AllowLiveTrading        = false;
input string TradeSymbol             = "AUDUSD";
input ENUM_TIMEFRAMES SignalTF       = PERIOD_M5;
input int    LookbackBars            = 48;
input int    ATRPeriod               = 14;
input double StopATRMult             = 2.0;
input double TakeProfitR             = 2.5;
input double RiskPercent             = 0.50;
input int    SessionStartHour        = 13;
input int    SessionEndHour          = 17;
input int    MaxSpreadPoints         = 25;
input int    MagicNumber             = 72404;
input int    MaxBarsHold             = 72;
input int    ATRRankBars             = 500;
input int    RangeRankBars           = 200;
input double ATRCompressionThreshold = 0.35;
input double RangeCompressionThresh  = 0.45;
input string LogFileName             = "AUDUSD_M5_CompressionBreakout_Paper.csv";

CTrade trade;
datetime lastBarTime = 0;
bool paperOpen = false;
int paperSide = 0;
datetime paperEntryTime = 0;
datetime paperEntryBarTime = 0;
double paperEntry = 0.0;
double paperSL = 0.0;
double paperTP = 0.0;
double paperRisk = 0.0;

int atrHandle = INVALID_HANDLE;
int ema21Handle = INVALID_HANDLE;
int ema55Handle = INVALID_HANDLE;

//+------------------------------------------------------------------+
int OnInit()
{
   if(_Symbol != TradeSymbol)
      Print("Warning: chart symbol is ", _Symbol, " but TradeSymbol input is ", TradeSymbol);

   atrHandle = iATR(TradeSymbol, SignalTF, ATRPeriod);
   ema21Handle = iMA(TradeSymbol, SignalTF, 21, 0, MODE_EMA, PRICE_CLOSE);
   ema55Handle = iMA(TradeSymbol, SignalTF, 55, 0, MODE_EMA, PRICE_CLOSE);

   if(atrHandle == INVALID_HANDLE || ema21Handle == INVALID_HANDLE || ema55Handle == INVALID_HANDLE)
   {
      Print("Failed to create indicator handles.");
      return INIT_FAILED;
   }

   trade.SetExpertMagicNumber(MagicNumber);
   EnsureLogHeader();
   Print("AUDUSD M5 Compression Breakout PAPER EA initialized. PaperMode=", PaperMode, " AllowLiveTrading=", AllowLiveTrading);
   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(atrHandle != INVALID_HANDLE) IndicatorRelease(atrHandle);
   if(ema21Handle != INVALID_HANDLE) IndicatorRelease(ema21Handle);
   if(ema55Handle != INVALID_HANDLE) IndicatorRelease(ema55Handle);
}

//+------------------------------------------------------------------+
void OnTick()
{
   if(_Symbol != TradeSymbol)
      return;

   datetime t = iTime(TradeSymbol, SignalTF, 0);
   if(t == 0)
      return;

   ManagePaperTrade();

   if(t == lastBarTime)
      return;
   lastBarTime = t;

   EvaluateClosedBar();
}

//+------------------------------------------------------------------+
void EvaluateClosedBar()
{
   int shift = 1; // closed candle
   if(Bars(TradeSymbol, SignalTF) < MathMax(ATRRankBars + 20, LookbackBars + 20))
      return;

   MqlDateTime dt;
   TimeToStruct(iTime(TradeSymbol, SignalTF, shift), dt);
   if(dt.hour < SessionStartHour || dt.hour >= SessionEndHour)
      return;

   int spread = (int)SymbolInfoInteger(TradeSymbol, SYMBOL_SPREAD);
   if(spread <= 0 || spread > MaxSpreadPoints)
      return;

   if(HasOpenPositionOrPaper())
      return;

   double atr = BufferValue(atrHandle, shift);
   double ema21 = BufferValue(ema21Handle, shift);
   double ema55 = BufferValue(ema55Handle, shift);
   if(atr <= 0 || ema21 <= 0 || ema55 <= 0)
      return;

   bool compression = IsCompressed(shift + 1);
   if(!compression)
      return;

   double close = iClose(TradeSymbol, SignalTF, shift);
   double hi = HighestHigh(shift + 1, LookbackBars);
   double lo = LowestLow(shift + 1, LookbackBars);

   int side = 0;
   if(close > hi && ema21 > ema55) side = 1;
   if(close < lo && ema21 < ema55) side = -1;
   if(side == 0)
      return;

   double ask = SymbolInfoDouble(TradeSymbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(TradeSymbol, SYMBOL_BID);
   double entry = side == 1 ? ask : bid;
   double risk = atr * StopATRMult;
   if(risk <= 0)
      return;

   double sl = side == 1 ? entry - risk : entry + risk;
   double tp = side == 1 ? entry + risk * TakeProfitR : entry - risk * TakeProfitR;

   string sideName = side == 1 ? "long" : "short";
   LogEvent("SIGNAL", sideName, entry, sl, tp, atr, spread, 0.0, "compression_breakout_signal");

   if(PaperMode || !AllowLiveTrading)
   {
      OpenPaper(side, entry, sl, tp, risk);
      return;
   }

   double lots = CalcLots(risk);
   if(lots <= 0)
   {
      LogEvent("LIVE_SKIP", sideName, entry, sl, tp, atr, spread, 0.0, "invalid_lot_size");
      return;
   }

   bool ok = side == 1 ? trade.Buy(lots, TradeSymbol, entry, sl, tp, "EdgeLab AUDUSD M5 compression")
                       : trade.Sell(lots, TradeSymbol, entry, sl, tp, "EdgeLab AUDUSD M5 compression");
   LogEvent(ok ? "LIVE_ORDER" : "LIVE_ERROR", sideName, entry, sl, tp, atr, spread, 0.0, ok ? "order_sent" : trade.ResultRetcodeDescription());
}

//+------------------------------------------------------------------+
bool IsCompressed(int shift)
{
   double atrNow = BufferValue(atrHandle, shift);
   if(atrNow <= 0) return false;

   int atrLess = 0, atrCount = 0;
   for(int i = shift; i < shift + ATRRankBars; i++)
   {
      double v = BufferValue(atrHandle, i);
      if(v <= 0) continue;
      atrCount++;
      if(v <= atrNow) atrLess++;
   }
   if(atrCount < 50) return false;
   double atrRank = (double)atrLess / (double)atrCount;

   double rangeNow = iHigh(TradeSymbol, SignalTF, shift) - iLow(TradeSymbol, SignalTF, shift);
   int rangeLess = 0, rangeCount = 0;
   for(int j = shift; j < shift + RangeRankBars; j++)
   {
      double r = iHigh(TradeSymbol, SignalTF, j) - iLow(TradeSymbol, SignalTF, j);
      if(r <= 0) continue;
      rangeCount++;
      if(r <= rangeNow) rangeLess++;
   }
   if(rangeCount < 50) return false;
   double rangeRank = (double)rangeLess / (double)rangeCount;

   return atrRank < ATRCompressionThreshold && rangeRank < RangeCompressionThresh;
}

//+------------------------------------------------------------------+
double HighestHigh(int startShift, int count)
{
   double v = -DBL_MAX;
   for(int i = startShift; i < startShift + count; i++)
      v = MathMax(v, iHigh(TradeSymbol, SignalTF, i));
   return v;
}

//+------------------------------------------------------------------+
double LowestLow(int startShift, int count)
{
   double v = DBL_MAX;
   for(int i = startShift; i < startShift + count; i++)
      v = MathMin(v, iLow(TradeSymbol, SignalTF, i));
   return v;
}

//+------------------------------------------------------------------+
double BufferValue(int handle, int shift)
{
   double buf[];
   ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, 0, shift, 1, buf) != 1)
      return 0.0;
   return buf[0];
}

//+------------------------------------------------------------------+
bool HasOpenPositionOrPaper()
{
   if(paperOpen) return true;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(!PositionSelectByTicket(ticket)) continue;
      if(PositionGetString(POSITION_SYMBOL) == TradeSymbol && PositionGetInteger(POSITION_MAGIC) == MagicNumber)
         return true;
   }
   return false;
}

//+------------------------------------------------------------------+
void OpenPaper(int side, double entry, double sl, double tp, double risk)
{
   paperOpen = true;
   paperSide = side;
   paperEntryTime = TimeCurrent();
   paperEntryBarTime = iTime(TradeSymbol, SignalTF, 0);
   paperEntry = entry;
   paperSL = sl;
   paperTP = tp;
   paperRisk = risk;
   LogEvent("PAPER_OPEN", side == 1 ? "long" : "short", entry, sl, tp, BufferValue(atrHandle, 1), (int)SymbolInfoInteger(TradeSymbol, SYMBOL_SPREAD), 0.0, "paper_trade_opened");
}

//+------------------------------------------------------------------+
int PaperBarsHeld()
{
   if(paperEntryBarTime <= 0)
      return 0;
   int shift = iBarShift(TradeSymbol, SignalTF, paperEntryBarTime, false);
   if(shift >= 0)
      return shift;
   int seconds = PeriodSeconds(SignalTF);
   if(seconds <= 0)
      seconds = 300;
   return (int)((TimeCurrent() - paperEntryTime) / seconds);
}

//+------------------------------------------------------------------+
void ManagePaperTrade()
{
   if(!paperOpen) return;

   double bid = SymbolInfoDouble(TradeSymbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(TradeSymbol, SYMBOL_ASK);
   double exitPrice = 0.0;
   string reason = "";
   int barsHeld = PaperBarsHeld();

   if(paperSide == 1)
   {
      if(bid <= paperSL) { exitPrice = paperSL; reason = "paper_sl"; }
      else if(bid >= paperTP) { exitPrice = paperTP; reason = "paper_tp"; }
      else if(barsHeld >= MaxBarsHold) { exitPrice = bid; reason = StringFormat("paper_timeout_%d_bars", barsHeld); }
   }
   else if(paperSide == -1)
   {
      if(ask >= paperSL) { exitPrice = paperSL; reason = "paper_sl"; }
      else if(ask <= paperTP) { exitPrice = paperTP; reason = "paper_tp"; }
      else if(barsHeld >= MaxBarsHold) { exitPrice = ask; reason = StringFormat("paper_timeout_%d_bars", barsHeld); }
   }

   if(reason == "") return;

   double r = paperSide * (exitPrice - paperEntry) / paperRisk;
   LogEvent("PAPER_CLOSE", paperSide == 1 ? "long" : "short", paperEntry, paperSL, paperTP, BufferValue(atrHandle, 1), (int)SymbolInfoInteger(TradeSymbol, SYMBOL_SPREAD), r, reason);
   paperOpen = false;
   paperSide = 0;
   paperEntryBarTime = 0;
}

//+------------------------------------------------------------------+
double CalcLots(double riskPrice)
{
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double riskMoney = equity * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(TradeSymbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(TradeSymbol, SYMBOL_TRADE_TICK_SIZE);
   if(riskMoney <= 0 || tickValue <= 0 || tickSize <= 0 || riskPrice <= 0)
      return 0.0;

   double lossPerLot = riskPrice / tickSize * tickValue;
   if(lossPerLot <= 0) return 0.0;

   double lots = riskMoney / lossPerLot;
   double minLot = SymbolInfoDouble(TradeSymbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(TradeSymbol, SYMBOL_VOLUME_MAX);
   double step = SymbolInfoDouble(TradeSymbol, SYMBOL_VOLUME_STEP);
   lots = MathMax(minLot, MathMin(maxLot, lots));
   lots = MathFloor(lots / step) * step;
   return NormalizeDouble(lots, 2);
}

//+------------------------------------------------------------------+
void EnsureLogHeader()
{
   int h = FileOpen(LogFileName, FILE_READ | FILE_CSV | FILE_ANSI);
   if(h != INVALID_HANDLE)
   {
      FileClose(h);
      return;
   }
   h = FileOpen(LogFileName, FILE_WRITE | FILE_CSV | FILE_ANSI);
   if(h == INVALID_HANDLE) return;
   FileWrite(h, "time", "event", "symbol", "tf", "side", "entry", "sl", "tp", "atr", "spread_points", "result_R", "note");
   FileClose(h);
}

//+------------------------------------------------------------------+
void LogEvent(string eventType, string side, double entry, double sl, double tp, double atr, int spread, double resultR, string note)
{
   int h = FileOpen(LogFileName, FILE_READ | FILE_WRITE | FILE_CSV | FILE_ANSI);
   if(h == INVALID_HANDLE)
   {
      Print("Could not open log file: ", LogFileName);
      return;
   }
   FileSeek(h, 0, SEEK_END);
   FileWrite(h, TimeToString(TimeCurrent(), TIME_DATE | TIME_SECONDS), eventType, TradeSymbol, EnumToString(SignalTF), side, DoubleToString(entry, 5), DoubleToString(sl, 5), DoubleToString(tp, 5), DoubleToString(atr, 6), spread, DoubleToString(resultR, 4), note);
   FileClose(h);
   Print(eventType, " ", side, " ", TradeSymbol, " R=", DoubleToString(resultR, 4), " ", note);
}
//+------------------------------------------------------------------+
